djangoAppsProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('inceptus.urls')),
    path('admin/', admin.site.urls),
]

inceptus/urls.py
from django.urls import path

from . import views

app_name = 'inceptus'

urlpatterns = [
    path('', views.index, name='index'),
    path('search', views.search, name='search'),
    path('query', views.query, name='query'),
    path('results', views.results, name='results'),
]

inceptus/models.py
from django.db import models

# Create your models here.

inceptus/views.py
import json

from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.urls import reverse

from library.search_engine.SearchEngine import SearchEngine
from library.search_engine.SearchResult import SearchResult


def index(request):
    return render(request, 'inceptus/index.html')


def query(request):
    q = request.GET.get('query', None)
    searchEngine = SearchEngine(q)
    data = searchEngine.searchResults
    # one = SearchResult("Ariana Grande - Wikipedia", "http://www.wikipedia.org", "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium adipisci aspernatur illo")
    # two = SearchResult("Ariana Grande - Wikipedia", "http://www.wikipedia.org", "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium adipisci aspernatur illo")
    # data = [one, two, one, one, one, one, one, two, one, one, one, one]
    return render(request, 'inceptus/results.html', {'data': data, 'query': q})
    # return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def results(request):
    q = request.GET['query']
    print("iiiiiiiiiiiiiiiiiiiiiiiiiiii")
    print(q)
    print("iiiiiiiiiiiiiiiiiiiiiiiiiiii")
    # searchEngine = SearchEngine("The Umbrella Academy")
    # data = searchEngine.searchResults
    return render(request, 'inceptus/index.html')


def search(request):
    searchEngine = SearchEngine("The Umbrella Academy")
    results = searchEngine.searchResults

    resultsDict = {}
    searchResults = []

    for result in results:
        title = result.title
        link = result.link
        extract = result.extract

        resultsObject = {
            "title": title,
            "link": link,
            "extract": extract
        }

        searchResults.append(resultsObject)

    lengthObject = {
        "length": len(searchResults)
    }
    resultsDict["length"] = lengthObject
    resultsDict["results"] = searchResults

    return JsonResponse(resultsDict)

inceptus/templates/inceptus/index.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
<title>Inceptus 😁- Johnson's Meta Search Engine</title>
{% endblock title %}

{% block style %}
    <link href="{% static 'inceptus/searchBar.css' %}" rel="stylesheet">
{% endblock style %}

{% block content %}
       <div class="container-fluid">
            <div class="p-5 text-center bg-white">
                <p class="text-center">
                    <img class="wow fadeInDown" src="{% static 'inceptus/img/cover.png' %}" style="width: 45%" alt="">
                </p>

                <form class="wrap" action="{% url 'inceptus:query' %}" method="get" style="display: inline-block">
                    {% csrf_token %}
                   <div class="search">
                      <input type="text" class="searchTerm  wow fadeIn" name="query" placeholder="" autofocus>
                      <button type="submit" class="searchButton  wow fadeInRight">
                        <i class="fa fa-search"></i>
                     </button>
                   </div>
                </form>
            </div>
       </div>

{% endblock content %}

inceptus/templates/inceptus/results.html
{% extends 'layout.html' %}
{% load static %}

{% block style %}
    <link href="{% static 'inceptus/searchBar.css' %}" rel="stylesheet">
    <style>
        body {
          background: linear-gradient(to right, #eef5f5, #f5fafa);
        }
    </style>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif&display=swap" rel="stylesheet">




{% endblock style %}

{% block title %}
<title>Results</title>
{% endblock title %}

{% block content %}
    <!--Navbar-->
<nav class="navbar navbar-expand-lg bg-white">

      <!-- Navbar brand -->
      <a class="navbar-brand" href="#">
          <img class="wow fadeIn" src="{% static 'inceptus/img/inspectus.png' %}" style="width: 100px;" alt="">
      </a>
      <form class="wrap" action="{% url 'inceptus:query' %}" method="get" style="display: inline-block; width: 50%">
          {% csrf_token %}
       <div class="search">
          <input type="text" class="searchTerm  wow fadeIn" name="query" placeholder="" value="{{ query }}" autofocus>
          <button type="submit" class="searchButton  wow fadeIn">
            <i class="fa fa-search"></i>
         </button>
       </div>
    </form>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">

{#        <!-- Links -->#}
{#        <ul class="navbar-nav mr-auto">#}
{#          <li class="nav-item active">#}
{#            <a class="nav-link" href="#">Home#}
{#              <span class="sr-only">(current)</span>#}
{#            </a>#}
{#          </li>#}
{#          <li class="nav-item">#}
{#            <a class="nav-link" href="#">Features</a>#}
{#          </li>#}
{#          <li class="nav-item">#}
{#            <a class="nav-link" href="#">Pricing</a>#}
{#          </li>#}
{##}
{#          <!-- Dropdown -->#}
{#          <li class="nav-item dropdown">#}
{#            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"#}
{#              aria-haspopup="true" aria-expanded="false">Dropdown</a>#}
{#            <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">#}
{#              <a class="dropdown-item" href="#">Action</a>#}
{#              <a class="dropdown-item" href="#">Another action</a>#}
{#              <a class="dropdown-item" href="#">Something else here</a>#}
{#            </div>#}
{#          </li>#}
{##}
{#        </ul>#}
{#        <!-- Links -->#}
{##}
{#        <form class="form-inline">#}
{#          <div class="md-form my-0">#}
{#            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">#}
{#          </div>#}
{#        </form>#}
      </div>
      <!-- Collapsible content -->

</nav>
    <!--/.Navbar-->
<div class="results-container">
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-7 pr-3">
                {% for searchResult in data %}
                <div class="result mb-3 wow slideInUp">
                    <div class="p-3 result-1 wow">
                        <h4 style="color: #4532ce" class="wow slideInDown">{{ searchResult.title }}</h4>
                        <!-- Link icon by Icons8 -->
                        <div class="d-flex" style="overflow-x: hidden">
<img class="icon icons8-Link" style="width: 20px; height: 20px" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAACc0lEQVRoQ+1YPWzTQBT+nlMJVcmKmoQiMVAkKuwWwVJGYGxGKhTUjvyKjTgd2FhKwoZUfkYqKgRbYUKUpYAYqGgd1AxFgqFNWrE2lRDED6XIbgKW6/TOoUbnzef33ve97zvfnU2I+EUR5w/VwL92UDmgHBBUQE0hQQGF05UDwhIKFlAOCAoonO7pwOHry/tq3bUR4pjBGgwwDwDocdAYqIBonsCLVEf5x6Y2823y2EY7bGRh/NVAb26pr679nATjbHBCtECEa5Xb+rsgOTIxWhroyZWGNeLnQUh4x9CVakG/75cvG8NtIGWWLgN8b/fkf2faTJn1ov7Cq04YGFsNpPOlU8z81gP0IWC/YY3n1iaOf3WeHzAXe+tMQ0SUAXj0z7wYdx1ZKfYvN4+HhUH7r35KdCV4DuDBFiIaTlYnjPmdHEnmrHNEeNoSR3gV3+we/ny373tjPEwMSt+wsqzhcTMBZoysFY1nO5F3nqfGrROw8aE13h6rFganthwOEYNSeesWGDe3wWmqWtDHgpJ3mzCtBwAuOvfEdKdS1HON+zAxKJkvzRBzxl3jA6h/ZnrDYNATMI6226hnPKFM4POz2YTlVy9lLowC2iM3huglJU1rlYC0M6iBD64WBlb8Cp2eri1JI+9ahvLrbLzfDzc5/vEQ2bEvTTHre6YBAt7PXogPtd/AHphCDfIgvrSrKRTmC9aRlzjMJa4jy2iYm0xHNrLIHyW2N6IIH+acJmQfdb2WRNkY/9cHjaOYrM89v01JFob6KyHlMCdQRDkgIJ6UVOWAFBkFiigHBMSTkqockCKjQBHlgIB4UlKVA1JkFCgSeQd+Acqx5UKvfJ02AAAAAElFTkSuQmCC" width="48" height="48">
                            <span class="ml-1">
                                <a style="color: #20692b; text-decoration: none" href="{{ searchResult.link }}">{{ searchResult.link }}</a>
                            </span>
                        </div>
                        <p class="extract">
                           {{ searchResult.extract }}
                        </p>
                    </div>
                </div>
                {% endfor %}
            </div>

{#            <div class="col-md-5 pl-3">#}
{#                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus commodi dicta dignissimos doloremque est harum ipsa labore laborum nisi obcaecati? Delectus doloribus, fugiat laborum minus ratione tempore totam veritatis. Distinctio.#}
{#            </div>#}
        </div>
    </div>
</div>

{% endblock content %}

inceptus/templates/layout.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/png" href="{% static 'inceptus/developer.png' %}"/>
    <meta property="og:title" content="Johnson's Meta Search Engine 😁">



    <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
{#      <link rel="stylesheet" href="{% static 'inceptus/bootstrap/css/bootstrap.min.css' %}">#}

      <!-- Bootstrap core CSS -->
      <link href="{% static 'inceptus/mdb/css/bootstrap.min.css' %}" rel="stylesheet">
      <!-- Material Design Bootstrap -->
      <link href="{% static 'inceptus/mdb/css/mdb.min.css' %}" rel="stylesheet">
      <!-- Your custom styles (optional) -->
        {% block title %}

        {% endblock title %}

      {% block style %}

      {% endblock style %}
      <link href="{% static 'inceptus/style.css' %}" rel="stylesheet">
  </head>
  <body>

  {% block content %}

  {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'inceptus/mdb/js/jquery.min.js' %}"></script>
    <script src="{% static 'inceptus/popper.min.js' %}"></script>
    <script src="{% static 'inceptus/bootstrap/js/bootstrap.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'inceptus/mdb/js/bootstrap.min.js' %}"></script>
      <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'inceptus/mdb/js/mdb.min.js' %}"></script>

  <script>
      $( document ).ready(function() {
          new WOW().init();
      });
  </script>

  </body>
</html>